### ISSUE TITLE
update bot bio based on github info

### ISSUE THREAD

**Issue by jaredallard** [Sweetie-Belle/FillyRT#1]
Add feature for bot too automatically detect version change and/or maintainer name change and update said features in bio.

Seems like that could be useful.

**Comment by jaredallard** [comment]
Anything? It's been two years :(

**Comment by Sweetie-Belle** [comment]
wontfix. :P fillyrt is being rewritten.

**Comment by jaredallard** [comment]
I waited two years for a won't fix. I'm crushed. </3
